[package]
name = "k0i"
version = "0.0.3"
edition = "2021"
license = "MIT"
authors = ["Соджиро Кояма <koyama10032009@outlook.jp> "]
description = "my competitive programming template"
documentation = "https://docs.rs/k0i_cp_template"
[dependencies]
