[package]
name = "k0i"
version = "0.0.11"
edition = "2021"
license = "MIT"
authors = ["Соджиро Кояма <koyama10032009@outlook.jp> "]
description = "my competitive programming template"
[dependencies]
rand = { version = "=0.7.3", features = ["small_rng"] }
